use bevy::prelude::*;

/// Bounds for a room on grid coordinates.
#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RoomBounds {
    pub min_x: i32,
    pub min_y: i32,
    pub max_x: i32,
    pub max_y: i32,
}

impl RoomBounds {
    pub fn from_tile(tile: (i32, i32)) -> Self {
        Self {
            min_x: tile.0,
            min_y: tile.1,
            max_x: tile.0,
            max_y: tile.1,
        }
    }

    pub fn include(&mut self, tile: (i32, i32)) {
        self.min_x = self.min_x.min(tile.0);
        self.min_y = self.min_y.min(tile.1);
        self.max_x = self.max_x.max(tile.0);
        self.max_y = self.max_y.max(tile.1);
    }
}

/// Logical room entity generated by room detection.
#[derive(Component, Debug, Clone)]
pub struct Room {
    pub tiles: Vec<(i32, i32)>,
    pub wall_tiles: Vec<(i32, i32)>,
    pub door_tiles: Vec<(i32, i32)>,
    pub bounds: RoomBounds,
    pub tile_count: usize,
}

/// Marker for visual overlay tiles spawned per room floor tile.
#[derive(Component, Debug, Clone, Copy, PartialEq, Eq)]
pub struct RoomOverlayTile {
    pub grid_pos: (i32, i32),
}
